### ISSUE TITLE
I bought the program, but I need help! 

### ISSUE THREAD

**Issue by brtraducoes** [YAL-GameMaker-Tools/BMFontToGMFont#1]
I need help converting the font to Gamemakerfile how should I do? 
test
http://prntscr.com/y2433c
http://prntscr.com/y2457p

Thank you!

**Comment by YellowAfterlife** [comment]
The [tutorial](https://yal.cc/gamemaker-text-shadow/) goes over the use of the tool a little - you need a GameMaker project with a font resource that you want to replace with a generated one; the executable to use depends on project version - ToGMX for 1.4, ToYY for GMS≤2.2.5, or ToYY23 for GMS≥2.3.
